"""Dashboards generated by a strategy: reading them, and setting one.

Every dashboard tool refused a strategy dashboard, reads included, so "what is
on my areas dashboard?" and "switch the Overview to the areas layout" had no
answer. A read now reports the strategy; setting one asks first when the
dashboard's own pages would be lost.
"""

from __future__ import annotations

from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.setup import async_setup_component
import pytest

from custom_components.selora_ai import dashboard_manager
from custom_components.selora_ai.const import DOMAIN
from custom_components.selora_ai.mcp_server import dispatch as mcp_dispatch
from custom_components.selora_ai.mcp_server.names import TOOL_SET_DASHBOARD_STRATEGY


ALL = ("original-states", "map", "iframe", "areas", "home", "energy")


@pytest.fixture
async def lovelace(hass: HomeAssistant) -> HomeAssistant:
    """With the strategies core 2026.9's frontend has (no frontend package here)."""
    assert await async_setup_component(hass, "lovelace", {"lovelace": {"mode": "storage"}})
    await hass.async_block_till_done()
    hass.data.setdefault(DOMAIN, {})["_frontend_strategies"] = ALL
    return hass


def _store(hass: HomeAssistant) -> Any:
    from homeassistant.components.lovelace.const import LOVELACE_DATA

    return hass.data[LOVELACE_DATA].dashboards[None]


async def _set(hass: HomeAssistant, **arguments: Any) -> dict[str, Any]:
    return await mcp_dispatch._get_tool_handlers()[TOOL_SET_DASHBOARD_STRATEGY](hass, arguments)


async def _read(hass: HomeAssistant) -> dict[str, Any]:
    return await mcp_dispatch._get_tool_handlers()["selora_get_dashboard"](hass, {})


async def test_a_generated_overview_switches_layout_directly(lovelace: HomeAssistant) -> None:
    result = await _set(lovelace, strategy={"type": "areas"})

    assert result["status"] == "updated", result
    assert await _store(lovelace).async_load(False) == {"strategy": {"type": "areas"}}
    read = await _read(lovelace)
    assert read["generated"] is True
    assert read["strategy"] == {"type": "areas"}


async def test_its_options_change_directly(lovelace: HomeAssistant) -> None:
    await _store(lovelace).async_save({"strategy": {"type": "areas"}})
    options = {"type": "areas", "areas_display": {"hidden": ["garage"]}}

    result = await _set(lovelace, strategy=options)

    assert result["status"] == "updated"
    assert (await _store(lovelace).async_load(False))["strategy"] == options


async def test_pages_of_its_own_are_lost_only_once_confirmed(lovelace: HomeAssistant) -> None:
    pages = {"views": [{"title": "Home", "cards": [{"type": "markdown", "content": "hi"}]}]}
    await _store(lovelace).async_save(pages)

    asked = await _set(lovelace, strategy={"type": "home"})
    assert asked["requires_confirmation"] is True
    assert asked["loses"] == {"views": 1, "cards": 1}
    assert await _store(lovelace).async_load(False) == pages

    done = await _set(
        lovelace, strategy={"type": "home"}, confirmed=True, fingerprint=asked["fingerprint"]
    )
    assert done["replaced"] == {"views": 1, "cards": 1}
    assert await _store(lovelace).async_load(False) == {"strategy": {"type": "home"}}


@pytest.mark.parametrize(
    ("strategy", "says"),
    [
        ({"type": "rooms"}, "not a dashboard strategy"),
        ({"type": "custom:Bad Name"}, "not a dashboard strategy"),
        ({"areas": True}, "with a type"),
        ("areas", "with a type"),
    ],
)
async def test_what_is_not_a_strategy_is_refused(
    lovelace: HomeAssistant, strategy: Any, says: str
) -> None:
    result = await _set(lovelace, strategy=strategy)

    assert says in result["error"]


async def test_a_custom_strategy_is_accepted(lovelace: HomeAssistant) -> None:
    result = await _set(lovelace, strategy={"type": "custom:mushroom-strategy"})

    assert result["status"] == "updated", result


async def test_a_dashboard_edited_since_it_was_shown_is_shown_again(
    lovelace: HomeAssistant,
) -> None:
    await _store(lovelace).async_save({"views": [{"title": "Home", "cards": []}]})
    asked = await _set(lovelace, strategy={"type": "areas"})
    edited = {"views": [{"title": "Home", "cards": [{"type": "markdown", "content": "new"}]}]}
    await _store(lovelace).async_save(edited)

    retry = await _set(
        lovelace, strategy={"type": "areas"}, confirmed=True, fingerprint=asked["fingerprint"]
    )

    assert retry["requires_confirmation"] is True
    assert "changed since it was shown" in retry["changed"]
    assert await _store(lovelace).async_load(False) == edited


async def test_views_kept_beside_a_strategy_survive_a_change(lovelace: HomeAssistant) -> None:
    """The frontend ignores them, but they are the user's."""
    document = {"strategy": {"type": "areas"}, "views": [{"title": "Old"}]}
    await _store(lovelace).async_save(document)

    await _set(lovelace, strategy={"type": "home"})

    assert await _store(lovelace).async_load(False) == {
        "strategy": {"type": "home"},
        "views": [{"title": "Old"}],
    }


async def test_a_strategy_this_frontend_lacks_is_refused(hass: HomeAssistant) -> None:
    """Without the frontend's own list, only the three every supported one has."""
    assert await async_setup_component(hass, "lovelace", {"lovelace": {"mode": "storage"}})
    await hass.async_block_till_done()

    result = await _set(hass, strategy={"type": "home"})

    assert "original-states, map, iframe" in result["error"]


def test_the_list_is_read_from_the_frontend_bundle(tmp_path: Any, monkeypatch: Any) -> None:
    import sys
    import types

    folder = tmp_path / "frontend_latest"
    folder.mkdir()
    (folder / "1.js").write_text("unrelated")
    (folder / "2.js").write_text(
        'const d={dashboard:{"original-states":()=>a.e(1),map:()=>a.e(2),'
        'areas:()=>Promise.all([a.e(3)]).then(x)},view:{"original-states":()=>a.e(4)}}'
    )
    monkeypatch.setitem(
        sys.modules, "hass_frontend", types.SimpleNamespace(where=lambda: str(tmp_path))
    )

    assert dashboard_manager._scan_frontend_strategies() == ("original-states", "map", "areas")
